DELETE FROM `seg_actividad_terceros`;
DELETE FROM `seg_certificaciones`;
DELETE FROM `seg_contratos`;
DELETE FROM `seg_contratos_enviados`;
DELETE FROM `seg_cotiza_tercero`;
DELETE FROM `seg_cotizaciones`;
DELETE FROM `seg_docs_contrato`;
DELETE FROM `seg_docs_tercero`;
DELETE FROM `seg_entrega_compra`;
DELETE FROM `seg_novedad_contrato_adi_pror`;
DELETE FROM `seg_novedad_contrato_cesion`;
DELETE FROM `seg_novedad_contrato_liquidacion`;
DELETE FROM `seg_novedad_contrato_reinicio`;
DELETE FROM `seg_novedad_contrato_suspension`;
DELETE FROM `seg_novedad_contrato_terminacion`;
DELETE FROM `seg_responsabilidades_terceros`;
DELETE FROM `seg_supervisor_designado`;
DELETE FROM `seg_valor_cotizacion`;
ALTER TABLE `seg_actividad_terceros` AUTO_INCREMENT = 1;
ALTER TABLE `seg_certificaciones` AUTO_INCREMENT = 1;
ALTER TABLE `seg_contratos` AUTO_INCREMENT = 1;
ALTER TABLE `seg_contratos_enviados` AUTO_INCREMENT = 1;
ALTER TABLE `seg_cotiza_tercero` AUTO_INCREMENT = 1;
ALTER TABLE `seg_cotizaciones` AUTO_INCREMENT = 1;
ALTER TABLE `seg_docs_contrato` AUTO_INCREMENT = 1;
ALTER TABLE `seg_docs_tercero` AUTO_INCREMENT = 1;
ALTER TABLE `seg_entrega_compra` AUTO_INCREMENT = 1;
ALTER TABLE `seg_novedad_contrato_adi_pror` AUTO_INCREMENT = 1;
ALTER TABLE `seg_novedad_contrato_cesion` AUTO_INCREMENT = 1;
ALTER TABLE `seg_novedad_contrato_liquidacion` AUTO_INCREMENT = 1;
ALTER TABLE `seg_novedad_contrato_reinicio` AUTO_INCREMENT = 1;
ALTER TABLE `seg_novedad_contrato_suspension` AUTO_INCREMENT = 1;
ALTER TABLE `seg_novedad_contrato_terminacion` AUTO_INCREMENT = 1;
ALTER TABLE `seg_responsabilidades_terceros` AUTO_INCREMENT = 1;
ALTER TABLE `seg_supervisor_designado` AUTO_INCREMENT = 1;
ALTER TABLE `seg_valor_cotizacion` AUTO_INCREMENT = 1;